import type { Rubric } from './types'

// Original built-in rubrics. They'll move to YAML files in `rubrics/` when the backend's
// rubric loader exists (Phase 2); until then the mock API serves them from here.

const LEVELS = ['Beginning', 'Developing', 'Proficient', 'Exemplary']

export const STARTER_RUBRICS: Rubric[] = [
  {
    id: 'argumentative-essay',
    version: 2,
    title: 'Argumentative essay',
    source: 'builtin',
    levels: LEVELS,
    summaries: {
      thesis: 'clear, arguable, answers the prompt',
      evidence: 'relevant, specific, cited',
      analysis: 'explains how evidence supports the claim',
      organization: 'logical order and transitions',
      conventions: 'grammar, spelling, citation format',
    },
    criteria: [
      {
        id: 'thesis',
        name: 'Thesis',
        type: 'score',
        weight: 1,
        question: 'How clear and arguable is the thesis, and does it answer the assignment prompt?',
        descriptors: [
          'No clear thesis, or the thesis only states a fact or topic',
          'A thesis is present but vague, or only partly answers the prompt',
          'A clear, arguable thesis that answers the prompt',
          'A precise, arguable thesis that frames the whole essay and anticipates complexity',
        ],
        tips: [
          'Write one sentence that states what you will argue, something a reader could disagree with.',
          'Make your thesis more specific: name exactly what changed, why, or for whom.',
          'Check that each body paragraph clearly connects back to your thesis.',
          'Keep it up. Make sure your conclusion shows how the essay proved the thesis.',
        ],
      },
      {
        id: 'evidence',
        name: 'Evidence',
        type: 'score',
        weight: 1,
        question:
          'How relevant, specific and well cited is the evidence used to support the argument?',
        descriptors: [
          'Little or no evidence, or evidence unrelated to the argument',
          'Some evidence, but it is general, thin or not cited',
          'Relevant, specific evidence in most paragraphs, with citations',
          'Well-chosen, specific evidence throughout, cited carefully and drawn from strong sources',
        ],
        tips: [
          'Add at least one specific fact, quote or example to each body paragraph.',
          'Replace general statements with a specific detail and say where it comes from.',
          'Look for the paragraph with the weakest evidence and swap in something more specific.',
          'Keep it up. Check that every citation matches the required format.',
        ],
      },
      {
        id: 'analysis',
        name: 'Analysis',
        type: 'score',
        weight: 1,
        question: 'How well does the essay explain how its evidence supports the thesis?',
        descriptors: [
          'Evidence is listed with no explanation',
          'Some explanation, but it mostly restates the evidence',
          'Explains most evidence and links it to the thesis',
          'Insightful analysis that deepens the argument',
        ],
        tips: [
          'Pick one quote and write two sentences on why it matters for your thesis.',
          'After each piece of evidence, explain in a sentence or two how it supports your thesis.',
          'Push one paragraph further: what does this evidence show that others miss?',
          'Keep it up. Check that every paragraph reaches this level.',
        ],
      },
      {
        id: 'organization',
        name: 'Organization',
        type: 'score',
        weight: 1,
        question:
          'How logically is the essay ordered, and how well do transitions connect its ideas?',
        descriptors: [
          'Ideas appear in no clear order and paragraphs do not connect',
          'Some order, but paragraphs often jump between ideas',
          'A logical order with clear topic sentences and transitions',
          'A purposeful structure where each paragraph builds on the last',
        ],
        tips: [
          'Outline your essay: write the main point of each paragraph in one line, then reorder.',
          'Start each body paragraph with a topic sentence that names its main point.',
          'Add a transition that shows how each paragraph relates to the one before it.',
          'Keep it up. Read your topic sentences in order to check they tell the whole argument.',
        ],
      },
      {
        id: 'conventions',
        name: 'Conventions',
        type: 'score',
        weight: 1,
        question:
          'How well does the essay follow conventions of grammar, spelling and citation format?',
        descriptors: [
          'Frequent errors make the essay hard to follow',
          'Noticeable errors, but the meaning is mostly clear',
          'Few errors, and they do not distract from the argument',
          'Polished writing with consistent, correct citation format',
        ],
        tips: [
          'Read your draft aloud slowly and mark every sentence that sounds off.',
          'Check one type of error at a time, such as commas, then spelling, then citations.',
          'Do a final pass focused only on citation format.',
          'Keep it up. A last read-through aloud will catch any small slips.',
        ],
      },
    ],
    checklist: [
      {
        id: 'thesis_first',
        name: 'Thesis appears in the first paragraph',
        question: 'Does the thesis appear in the first paragraph?',
      },
      {
        id: 'evidence_every_body',
        name: 'Every body paragraph uses evidence',
        question: 'Does every body paragraph use evidence?',
      },
      {
        id: 'counterargument',
        name: 'Addresses a counterargument',
        question: 'Does the essay address a counterargument?',
      },
    ],
    rules: { word_count: { min: 500, max: 900 } },
  },
  {
    id: 'lab-report',
    version: 1,
    title: 'Lab report',
    source: 'builtin',
    levels: LEVELS,
    summaries: {
      purpose: 'question and hypothesis are clear',
      methods: 'someone else could repeat it',
      results: 'data presented clearly and accurately',
      discussion: 'results interpreted, not just restated',
      error: 'limits and sources of error considered',
      style: 'concise, objective scientific writing',
    },
    criteria: [
      {
        id: 'purpose',
        name: 'Purpose',
        type: 'score',
        weight: 1,
        question:
          'How clearly does the report state the research question and a testable hypothesis?',
        descriptors: [
          'No research question or hypothesis',
          'A question or hypothesis is present but vague or not testable',
          'A clear question and a testable hypothesis',
          'A focused question and a testable hypothesis grounded in background science',
        ],
        tips: [
          'Write one sentence starting "This experiment tests whether…".',
          'Rewrite your hypothesis as "If…, then…, because…".',
          'Add a sentence of background explaining why you expected this result.',
          'Keep it up. Make sure the conclusion answers this exact question.',
        ],
      },
      {
        id: 'methods',
        name: 'Methods',
        type: 'score',
        weight: 1,
        question: 'Could another person repeat the experiment from the methods described?',
        descriptors: [
          'Methods are missing or too brief to follow',
          'Some steps are described, but key details are missing',
          'Steps, materials and variables are described clearly',
          'Complete, precise methods with controls and variables clearly identified',
        ],
        tips: [
          'List every step you took in order, as if someone else had to repeat it.',
          'Add quantities, times and equipment to each step.',
          'Name your independent, dependent and controlled variables.',
          'Keep it up. Check that units are given for every measurement.',
        ],
      },
      {
        id: 'results',
        name: 'Results',
        type: 'score',
        weight: 1,
        question: 'How clearly and accurately does the report present its data?',
        descriptors: [
          'Little or no data is reported',
          'Data is reported but hard to read, or tables and graphs lack labels',
          'Data is presented clearly with labeled tables or graphs',
          'Data is presented clearly and the key patterns are pointed out without interpretation',
        ],
        tips: [
          'Add a table with your measurements, including units.',
          'Give every table and graph a title and labeled axes or columns.',
          'Write one sentence that points out the main pattern in your data.',
          'Keep it up. Check that the text and the tables report the same numbers.',
        ],
      },
      {
        id: 'discussion',
        name: 'Discussion',
        type: 'score',
        weight: 1,
        question:
          'How well does the discussion interpret the results in relation to the hypothesis?',
        descriptors: [
          'Results are not discussed',
          'Results are restated but not interpreted',
          'Results are interpreted and linked to the hypothesis',
          'Results are interpreted using scientific reasoning and compared with expected values',
        ],
        tips: [
          'Say whether your results support your hypothesis, and point to the data that shows it.',
          'Explain why you think you got these results, not just what they were.',
          'Compare your results with an expected or published value.',
          'Keep it up. Suggest a follow-up experiment your results point to.',
        ],
      },
      {
        id: 'error',
        name: 'Error analysis',
        type: 'score',
        weight: 1,
        question: 'How well does the report identify limitations and sources of error?',
        descriptors: [
          'No discussion of error or limitations',
          'Mentions error in general terms, such as "human error"',
          'Identifies specific sources of error and their likely effect',
          'Identifies specific errors, estimates their effect and suggests improvements',
        ],
        tips: [
          'Name one specific thing that could have made your measurements less accurate.',
          'Replace "human error" with the exact step where a mistake could happen.',
          'Explain whether each error would make your results too high or too low.',
          'Keep it up. Suggest a concrete change to the method that reduces the biggest error.',
        ],
      },
      {
        id: 'style',
        name: 'Scientific style',
        type: 'score',
        weight: 1,
        question: 'How concise, objective and correctly formatted is the scientific writing?',
        descriptors: [
          'Informal or unclear writing, sections missing',
          'Mostly clear, but informal in places or sections out of order',
          'Clear, objective writing with all sections in order',
          'Concise, precise and objective writing that follows the format exactly',
        ],
        tips: [
          'Make sure the report has every section: purpose, methods, results, discussion.',
          'Replace personal phrases like "I think" with what the data shows.',
          'Cut words that do not add information.',
          'Keep it up. Check units, significant figures and formatting one last time.',
        ],
      },
    ],
    checklist: [
      {
        id: 'has_hypothesis',
        name: 'States a hypothesis',
        question: 'Does the report state a hypothesis?',
      },
      {
        id: 'units',
        name: 'Gives units for measurements',
        question: 'Are units given for the measurements?',
      },
    ],
    rules: { word_count: { min: 600, max: 1500 } },
  },
  {
    id: 'research-paper',
    version: 1,
    title: 'Research paper',
    source: 'builtin',
    levels: LEVELS,
    summaries: {
      question: 'focused, researchable question',
      sources: 'credible and varied sources',
      synthesis: 'sources in conversation, not a list',
      argument: 'a clear position built from research',
      structure: 'logical sections and flow',
      citation: 'consistent, complete citations',
      voice: 'clear, academic, your own words',
    },
    criteria: [
      {
        id: 'question',
        name: 'Research question',
        type: 'score',
        weight: 1,
        question: 'How focused and researchable is the paper’s central question?',
        descriptors: [
          'No clear research question',
          'A question that is too broad or too narrow to research well',
          'A focused, researchable question',
          'A focused question that matters and is framed within existing research',
        ],
        tips: [
          'Write your topic as a question that starts with "how" or "why".',
          'Narrow your question to a specific time, place or group.',
          'Explain in one sentence why the question matters.',
          'Keep it up. Make sure every section helps answer the question.',
        ],
      },
      {
        id: 'sources',
        name: 'Sources',
        type: 'score',
        weight: 1,
        question: 'How credible, relevant and varied are the sources used?',
        descriptors: [
          'Few sources, or sources that are not credible',
          'Some credible sources, but few or all of one kind',
          'Credible, relevant sources of more than one kind',
          'A strong, varied set of credible sources, including primary or scholarly work',
        ],
        tips: [
          'Replace any source without a clear author or publisher.',
          'Add a source of a different kind, such as a study, a primary source or a book.',
          'Add one scholarly or primary source that speaks directly to your question.',
          'Keep it up. Briefly explain why your key sources can be trusted.',
        ],
      },
      {
        id: 'synthesis',
        name: 'Synthesis',
        type: 'score',
        weight: 1,
        question:
          'How well does the paper connect sources to each other rather than summarizing them one by one?',
        descriptors: [
          'Sources are summarized one at a time with no connection',
          'Some connections, but mostly source-by-source summary',
          'Sources are compared and connected around ideas',
          'Sources are woven together to build new insight',
        ],
        tips: [
          'Organize a paragraph around an idea, not a source, and bring in two sources.',
          'Add a sentence showing where two sources agree or disagree.',
          'Explain what the sources together show that none shows alone.',
          'Keep it up. Check that your own voice leads each paragraph.',
        ],
      },
      {
        id: 'argument',
        name: 'Argument',
        type: 'score',
        weight: 1,
        question: 'How clearly does the paper take and support a position based on its research?',
        descriptors: [
          'No clear position',
          'A position is stated but weakly supported',
          'A clear position supported by the research',
          'A nuanced position that addresses counterevidence',
        ],
        tips: [
          'Write one sentence stating what your research leads you to conclude.',
          'Link each main section back to your position.',
          'Address one piece of evidence that complicates your position.',
          'Keep it up. Make sure your conclusion says what your answer means.',
        ],
      },
      {
        id: 'structure',
        name: 'Structure',
        type: 'score',
        weight: 1,
        question: 'How logical is the organization of sections and paragraphs?',
        descriptors: [
          'No clear structure',
          'Some structure, but sections are out of order or unbalanced',
          'Logical sections with clear transitions',
          'A structure that guides the reader through the argument',
        ],
        tips: [
          'Outline the paper by listing the point of each section.',
          'Add headings or topic sentences that signal each section’s purpose.',
          'Add transitions that explain how each section builds on the last.',
          'Keep it up. Check that the introduction previews the structure.',
        ],
      },
      {
        id: 'citation',
        name: 'Citation',
        type: 'score',
        weight: 1,
        question: 'How consistent and complete are in-text citations and the reference list?',
        descriptors: [
          'Citations are missing',
          'Some citations, but many are incomplete or inconsistent',
          'Consistent citations with a matching reference list',
          'Complete, correctly formatted citations throughout',
        ],
        tips: [
          'Add an in-text citation after every fact or quote from a source.',
          'Choose one citation style and make every citation match it.',
          'Check that every in-text citation appears in the reference list.',
          'Keep it up. Do a final check of the reference list order and format.',
        ],
      },
      {
        id: 'voice',
        name: 'Academic voice',
        type: 'score',
        weight: 1,
        question: 'How clear and academic is the writing, and is it in the author’s own words?',
        descriptors: [
          'Unclear writing, or heavy reliance on copied wording',
          'Mostly clear, but informal or leaning on quotes',
          'Clear academic writing, mostly in the author’s own words',
          'Precise, confident academic writing in the author’s own voice',
        ],
        tips: [
          'Put long quotes into your own words and cite them.',
          'Replace informal words with precise ones.',
          'Cut quotes where your own explanation would be stronger.',
          'Keep it up. Read one section aloud to check the flow.',
        ],
      },
    ],
    checklist: [
      {
        id: 'has_references',
        name: 'Includes a reference list',
        question: 'Does the paper include a reference list or bibliography?',
      },
      {
        id: 'counterevidence',
        name: 'Discusses counterevidence',
        question: 'Does the paper discuss evidence that goes against its position?',
      },
    ],
    rules: { word_count: { min: 1500, max: 3000 } },
  },
]
